### ISSUE TITLE
Readme states that crono works with rails 3.2.3, but the gemspec requires ActiveJob which doesn't exist in 3.2.3 

### ISSUE THREAD

**Issue by tomhealey** [plashchynski/crono#25]
Please fix the documentation.
 I would really like to use crono, but I can't move to 4.0 yet.

**Comment by plashchynski** [comment]
Hello @tomhealey 
you can use master, where we've removed the active job dependency.

**Comment by tomhealey** [comment]
Thanks.
I did pull the repo.
I built a local gem without the dependency but had trouble with that also.
No worries.
Thanks for the response.
I had to move to another alternative.

Tom Healey

On May 14, 2015, at 5:33 AM, Dzmitry Plashchynski <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @tomhealey<https://github.com/tomhealey>
you can use master, where we've removed the active job dependency.

�

**Comment by plashchynski** [comment]
@tomhealey np, feel free to submit an issue about the trouble.
