### ISSUE TITLE
DB connection pool issue.

### ISSUE THREAD

**Issue by ChandravatiSG** [plashchynski/crono#27]
When the script runs, getting error..

could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)

**Comment by chasseurmic** [comment]
There is definitely a problem with DB connection pool. After a while jobs get stuck because pool connections are not being released. Any plans to fix the issue?Thanks!

**Comment by plashchynski** [comment]
Hello @chasseurmic, please upgrade and let me know if the issue exists with a new version.
