### ISSUE TITLE
Run crono automatically with rails s 

### ISSUE THREAD

**Issue by lebart** [plashchynski/crono#29]
Hello,

Tanks for this gem, very simple to use! 

To test it, I just add it to a brand new rails app, at first I was waiting in front of the console to see the first test (print something) to appears... Nothing appends 

I figure it out latter that I have to run bundle exec crono. 

Is there any possibilities to make crono runs/launches when you start your rails server? Or maybe I'm missing something.

**Comment by Epigene** [comment]
You may use an initializer that startes crono daemonized, but this can be a source of headache, since you will still have to handle shutting crono down.

**Comment by lebart** [comment]
After some comparisons, especially with Rufus-scheduler, that's what I figured out. I agreed with you this can be tricky to shut down if started with an initializer. 

The project is really nice for "monitoring" some tasks directly out of the box!
