### ISSUE TITLE
Trouble daemonizing crono on production Ubuntu server

### ISSUE THREAD

**Issue by Epigene** [plashchynski/crono#30]
If I run `bundle exec crono -e production` in project root on production server, it works.  
`ps aux | grep crono` also returns the process

However, if I try to daemonize the process (so I can write mina deployment task), it fails silently.  
I have tried:
```
bundle exec crono -e production -d
bundle exec crono -e production -d true
bundle exec crono -e production --daemonize
bundle exec crono -e production --daemonize true
bundle exec crono -d -e production
bundle exec crono -d true -e production
bundle exec crono --daemonize -e production
bundle exec crono --daemonize true -e production
```

`ps aux | grep crono` returns only the grep process after every one of those commands.  
What is going on?

**Comment by plashchynski** [comment]
Hello @Epigene 
Could you check the log located at `log/crono.log`. Thank you.

**Comment by Epigene** [comment]
Right, `No such file or directory @ rb_sysopen ...`
Crono could not access the default pidfile location at tmp/pids/crono.pid

Changed command to

```
bundle exec crono -e production -d --pidfile ../../shared/pids/crono.pid
```
