### ISSUE TITLE
Crono did job but in dashboard it show: Never performed yet.

### ISSUE THREAD

**Issue by imgarylai** [plashchynski/crono#31]
I have four workers perform every 600 seconds. The result is perfect.  I didn't get any error messages. However, In the dashboard one of workers always show: Never performed yet. Although this didn't effect the result, sometimes, workers suspend without error message. It's hard to track what happened. 

Should I provide any information to figure out the problem?

**Comment by plashchynski** [comment]
Hello @imgarylai 
Fixed in the new version 1.0.1 God catch btw.
