### ISSUE TITLE
table_name_prefix not taken into account

### ISSUE THREAD

**Issue by hjansen** [plashchynski/crono#33]
Hi,

in my application.rb file i used 

config.active_record.table_name_prefix = 'xyz_'

to create a namespace inside a database that is allreay in use by other applications as well.

When i try to start the crono job on commandline it says that it cannot find the table CRONO_JOBS which is correct because the table name is xyz_crono_jobs.

Is this a bug or do i have to set some options somewhere to make this work ?

Thx and greetings

Holger

**Comment by plashchynski** [comment]
@hjansen thanks for reporting.
