### ISSUE TITLE
Documentation on how to set this up in a production environment

### ISSUE THREAD

**Issue by jmatsuba** [plashchynski/crono#39]
I got setup on my developer environment pretty quickly. Now I want to get this running on production and am wondering what the best way to do it is.

Including this as part of the README.md would be helpful.

**Comment by cwills** [comment]
Did you get this working in production? I've been struggling with this.

**Comment by jmatsuba** [comment]
i did not, i ended up abandoning it and doing straight cron jobs.

I used this tutorial
http://tutorials.jumpstartlab.com/topics/systems/automation.html

**Comment by plashchynski** [comment]
There's a Capistrano integration for production https://github.com/plashchynski/crono#capistrano

**Comment by skyamgar** [comment]
I am not using Capistrano, Can anybody help with how to setup this in production environment on VPS?
