### ISSUE TITLE
Documentation: how to start crono

### ISSUE THREAD

**Issue by brunofacca** [plashchynski/crono#57]
Thanks fo the great gem!

The documentation only explains how to start crono from the command line. I'd like to have it autostarted with a Rails project instead of creating a Linux init script or something. Can it start automatically when Rails is started? Do we need to create an initializer? What are the consequences of running as a daemon vs. not running it as a daemon?

Again, thank you.

**Comment by plashchynski** [comment]
Hello @brunofacca 

you can start it using [foreman](https://github.com/ddollar/foreman)

With a Procfile like:
`
web: bundle exec puma -C config/puma.rb
crono: bundle exec crono
`
then:
`foreman start`

**Comment by brunofacca** [comment]
Thank you @plashchynski
