### ISSUE TITLE
hamlit-rails breaks the U.I

### ISSUE THREAD

**Issue by SaimonL** [plashchynski/crono#83]
I use the gem "hamlit-rails" which is 2 to 3 times faster then haml. The gem "hamlit-rails" is a drop in replacement for haml and it works fine. When I use the web U.I for crono it does not parse the html code. I tried adding "haml" gem and the problem was NOT solved. Then I commented out the "hamlit-rails" gem and then it worked. Is there a way to make this work with "hamlit-rails" gem instead?

**Comment by plashchynski** [comment]
Hello @SaimonL. Please check the new version of the gem (2.0.0), it does not depend on haml-rails.
